"""Initial migration

Revision ID: e7b9aa1bc9bd
Revises: 
Create Date: 2025-06-23 11:23:15.556623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b9aa1bc9bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('ciphertext', sa.BLOB(), nullable=False),
    sa.Column('iv', sa.BLOB(), nullable=False),
    sa.Column('aes_key', sa.BLOB(), nullable=False),
    sa.Column('otp_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('recipient_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('auto_sent', sa.BOOLEAN(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    # ### end Alembic commands ###
